export type ExerciseType = "anaerobic" | "aerobic";

export type Exercise = {
  name: string,
  type: ExerciseType,
  duration_min?: number | string,
  distance?: number | string,
  weight?: number | string,
  sets?: number | string,
  reps?: number | string,
}

export const EXERCISES: Record<string, Exercise> = {
  "biking": {
    name: "biking",
    type: "aerobic",
    duration_min: 25,
    distance: 9,
  },
  "forearm stretch": {
    name: "forearm stretch",
    type: "aerobic",
  },
  "hand grippers": {
    name: "hand grippers",
    type: "anaerobic",
    weight: 20,
    sets: 3,
    reps: 10,
  },
  "wrist curls": {
    name: "wrist curls",
    type: "anaerobic",
    weight: 3,
    sets: 3,
    reps: 10,
  },
  "wrist curls (reverse)": {
    name: "wrist curls (reverse)",
    type: "anaerobic",
    weight: 3,
    sets: 3,
    reps: 10,
  },
  "bicep curls": {
    name: "bicep curls",
    type: "anaerobic",
    weight: 15,
    sets: 3,
    reps: 10,
  },
  "dumbbell row": {
    name: "dumbbell row",
    type: "anaerobic",
    weight: 15,
    sets: 3,
    reps: 10,
  },
  "tricep curls": {
    name: "tricep curls",
    type: "anaerobic",
    weight: 10,
    sets: 3,
    reps: 10,
  },
  "shoulder presses": {
    name: "shoulder presses",
    type: "anaerobic",
    weight: 15,
    sets: 3,
    reps: 10,
  },
  "chest presses": {
    name: "chest presses",
    type: "anaerobic",
    weight: 20,
    sets: 3,
    reps: 10,
  },
  "butterfly cross": {
    name: "butterfly cross",
    type: "anaerobic",
    weight: 10,
    sets: 3,
    reps: 10,
  },
  "lunges": {
    name: "lunges",
    type: "anaerobic",
    weight: 20,
    sets: 3,
    reps: 10,
  },
  "squats": {
    name: "squats",
    type: "anaerobic",
    weight: 20,
    sets: 3,
    reps: 10,
  },
  "heel raises": {
    name: "heel raises",
    type: "anaerobic",
    weight: 20,
    sets: 3,
    reps: 10,
  },
  "situps": {
    name: "situps",
    type: "anaerobic",
    weight: 0,
    sets: 3,
    reps: 20,
  },
  "bicycle crunches": {
    name: "bicycle crunches",
    type: "anaerobic",
    weight: 0,
    sets: 3,
    reps: 20,
  },
  "leg raises": {
    name: "leg raises",
    type: "anaerobic",
    weight: 0,
    sets: 3,
    reps: 20,
  },
};
